version: "3.9"
services:
  userms:
    container_name: userms
    build: .
#    image: "de0ad7efebab"
    ports:
      - "8081:8081"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: [
        "--config.file=/etc/prometheus/prometheus.yml"
    ]

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000

