server:
  port: 8082

spring:
  application:
    name: orderms-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      ordermsService:
        sliding-window-size: 10
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 1
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 5s
