version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.54.1
    container_name: prometheus
    network_mode: host
#    ports:
#      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: docker.io/grafana/grafana:11.2.2
    container_name: grafana
#    ports:
#      - "3000:3000"
    network_mode: host
    volumes:
      - ./configs/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./configs/firstrestms-postgresql-dashboard_addstudents.json:/etc/grafana/provisioning/dashboards/firstrestms-postgresql-dashboard.json
      - ./configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin