spring:
  application:
    name: userms-client

  cloud:
    circuitbreaker:
      http-services:
        enabled: true # Enables the native adapter integration


server:
  port: 8082

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: false
    hostname: localhost

# Actuator (to visualize circuit breaker states)
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
      sampling:
        probability: 1.0

    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs



logging:
  level:
    com.example.userms_client: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      usermsclient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
      userByIdclient:
        ignore-exceptions:
          - com.example.userms_client.UserNotFoundException
          - com.example.userms_client.BadRequestForUserIdException
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
      helloService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 15s
        automatic-transition-from-open-to-half-open-enabled: true