spring.application.name=oauth2-client-github

spring.security.oauth2.client.registration.github.clientId=0c20ffd7f555b7075622
spring.security.oauth2.client.registration.github.clientSecret=712b81bd67f6047d678b51b390ad9b2ad562b08d
