version: "3.9"
services:
  clientuserms:
    container_name: client-userms
    image: "dellubuntu/client-userms:1.0.0-SNAPSHOT"
    ports:
      - 8082:8082
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: [
        "--config.file=/etc/prometheus/prometheus.yml"
    ]

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
